name: Update Table Info
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  update-info:
    name: Update Info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      
      - name: Sync dependencies
        run: uv sync
      
      - name: Run gen_tables
        run: uv run scripts/gen_tables.py
      
      - name: Run gen_data_md
        run: uv run scripts/gen_data_md.py
      
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.AUTOMERGE_TOKEN }}
          commit-message: "automated: Update Info"
          title: "automated: Update Info"
          body: |
            Auto Update Info
          branch: update-info
          labels: |
            automated
            update-info

      - name: Merge Pull Request
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        run: |
          PR_NUMBER='${{ steps.create-pull-request.outputs.pull-request-number }}'
          echo "启用PR #$PR_NUMBER 的自动合并"
          gh pr merge "$PR_NUMBER" --auto --squash
